# -*- mode= ruby -*-
# vi: set ft=ruby :

#configuraciones basicas 
VERSION_VANGRANT = "2" 

NAME_BOX = "bento/ubuntu-16.04"
#configuracione de la network
HOST_NAME="red.local"
GUEST = "80"
HOST = "8080"
PRIVATE_NET_BOX= "192.168.33.101"



#Siempre poner vagrant para iniciar y luego la version, pasamos las configuraciones de la box
Vagrant.configure(VERSION_VANGRANT) do |config|

    ##
    # BOXRED1
    ##
    
    config.vm.define "br1" do |br1|
      br1.vm.box = NAME_BOX
      br1.vm.network "private_network", ip: PRIVATE_NET_BOX

      #configuraciones de virtual box
      br1.vm.provider "virtualbox" do |vb|
        vb.gui = false
        vb.name = "boxred1.box"
        vb.memory = "1024"
        #vb.cpus = 1
      end
      
      # br1.vm.provision :shell, path: "conf/bootstrap-red.sh"
      br1.vm.provision :shell, inline: <<-SHELL
      sudo apt-get update
      sudo apt-get -y upgrade
      SHELL

    end


    ##
    # BOXRED2
    ##
    config.vm.provider "br2" do |br2|
    file_to_disk = 'tmp/disk.vdi'
    unless File.exist?(file_to_disk)
      br2.customize [
                    'createhd',
                    '--filename', file_to_disk,
                    '--size', 500 * 1024
                    ]
    end
    br2.customize [
                  'storageattach', :id,
                  '--storagectl', 'SATAController',
                  '--port', 1,
                  '--device', 0,
                  '--type', 'hdd',
                  '--medium', file_to_disk
                  ]
    end
    
  end